version: "3.1"
services:
  web:
    image: odoo:latest
    depends_on:
      - db
    ports:
      - "${PORT}:8069"
      - "8072:8072"
    environment:
      - PORT=5432
      - DATABASE=${DATABASE}
      - HOST=${HOST}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
